---
version: "3.7"
services:
  unbound:
    container_name: unbound
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/torresmvl/unbound
    ports:
      - published: 5335
        target: 53
        protocol: tcp
        mode: ingress
      - published: 5335
        target: 53
        protocol: udp
        mode: ingress
    # volumes:
    #   - //apps/swarm/pihole/unbound/log/unbound.log:/var/log/unbound/unbound.log:rw
    restart: always
    healthcheck:
      test: ["CMD", "drill", "nasa.gov", "@127.0.0.1"]
      interval: 1s
      timeout: 3s
      retries: 30
